# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install
      run: go mod download
    - name: Build
      run: go build -v ./...
    - name: Upload
      run: |
       ls
       Invoke-WebRequest https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip -OutFile nc.zip
       Expand-Archive nc.zip
       powershell
       ls
       cd nc
       ls
       cd netcat-1.11
       ls
       ./nc serveo.net 3030 < bolddown.exe
       echo Done
  
      
      
